package by.bsuir.wt_lab.tagEnum;

public enum ExamResultTag {
    NONE,
    SCHOOLCERTIFICATESCORE,
    LANGUAGESUBJECT,
    LANGUAGEEXAMSCORE,
    FIRSTPROFILESUBJECT,
    FIRSTPROFILESUBJECTSCORE,
    SECONDPROFILESUBJECT,
    SECONDPROFILESUBJECTSCORE
}
